### ISSUE TITLE
build: using VC-LTL5

### ISSUE THREAD

**Issue by myfreeer** [myfreeer/7z-build-nsis#19]
Link: <https://github.com/Chuyu-Team/VC-LTL5>
This should be after #17 and #21 
This should not be merged before commit https://github.com/Chuyu-Team/VC-LTL5/commit/fe7d94e0095dd199e14bcf64ac8d0235a69dfb25 reaches a stable release.

**Comment by MouriNaruto** [comment]
First of all, thank you very much because I have used your branch in [NanaZip](https://github.com/M2Team/NanaZip/stargazers).

I want to give you some notice about VC-LTL 5.x Series: If you want to enable Windows XP/2003 support for VC-LTL 5.x Series. You also need [YY-Thunks](https://github.com/Chuyu-Team/YY-Thunks).

Kenji Mouri

**Comment by myfreeer** [comment]
@MouriNaruto Thank you for reporting this. Is `YY-Thunks` needed if 7-zip does not use new API introduced in Vista or later?

**Comment by MouriNaruto** [comment]
@myfreeer 

> Is `YY-Thunks` needed if 7-zip does not use new API introduced in Vista or later?

Yes, because the MSVC part (e.g. VCRuntime and STL) uses the new API (e.g. SRW lock and new locale API) introduced introduced even in 7 or later.

Kenji Mouri

**Comment by myfreeer** [comment]
@MouriNaruto 

> Yes, because the MSVC part (e.g. VCRuntime and STL) uses the new API (e.g. SRW lock and new locale API) introduced even in 7 or later.

Is the `MSVC part` introduced by `VC-LTL5` or windows sdk 10.x or 7-zip?

**Comment by MouriNaruto** [comment]
@myfreeer 

> Is the `MSVC part` introduced by `VC-LTL5` or windows sdk 10.x or 7-zip?

Nope, VC-LTL 5.x only wraps the UCRT and VCRuntime (because `UCRT` have the same part) to msvcrt.dll or ucrtbase.dll. Windows 10 SDK only maintains the UCRT. 

I don't know STL or other VCRT part needed in 7-Zip. 

I think you can try to compile 7-Zip with VC-LTL 5.x first. If you find some functions lacked, you can use YY-Thunks to solve. 

Kenji Mouri

**Comment by MouriNaruto** [comment]
@myfreeer 

Also, you can read https://github.com/Chuyu-Team/VC-LTL5#24-supported-windows-versions.

Kenji Mouri

**Comment by myfreeer** [comment]
@MouriNaruto Thank you for reporting this.
