### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by musm** [myfreeer/7z-build-nsis#6]
How is this different from nsis? It looks interesting but I'm not exactly sure how it differs.

**Comment by myfreeer** [comment]
This build can unpack nsis script, eg. `[NSIS].nsi` or `[LICENSE].txt` from nsis installer. This feature is disable in official versions since `15.05`, after which official versions are only able to unpack files from installer.

Also, check <https://sourceforge.net/p/sevenzip/discussion/45797/thread/5d10a376/>
